version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'techstore'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.0.7
    ports:
      - "6379:6379"
    
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "node src/lib/sequelize.js && npm run dev"
    environment:
      DB_HOST: db
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: techstore
    volumes:
      - .:/app
      
volumes:
  db_data:
